name: Check default rules validity

on:
  schedule:
    - cron: '0 0 * * *' # This will run the test every day at midnight
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: npx playwright test tests/e2e/external/default-rules-validity.spec.js

env:
  USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
  USER_USERNAME: ${{ secrets.TEST_USER_USERNAME }}